spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security
    username: secuser
    password: secuserpwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

### Application Port No ###
server:
  port: 8085

#
#### Logging level config ###
logging.level.org.springframework.web: DEBUG
logging.level.web: DEBUG
logging.level.org.springframework.security: DEBUG
logging.level.com.berriesoft.springsecurity: DEBUG

#### SPRING Actuator config ###
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,env,beans,mappings"
    env:
      show-values: WHEN_AUTHORIZED
    configprops:
      show-values: WHEN_AUTHORIZED



